### ISSUE TITLE
Support of sub facts 

### ISSUE THREAD

**Issue by evgenkisel** [theforeman/foreman_default_hostgroup#45] opened 2020-08-25 15:11 UTC
Hi! 

Does the plugin support to use facts like os.name or os.family ?
The Facter allows a structure like:
`# facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.7",
    major => "7",
    minor => "7"
  },
  selinux => {
    enabled => false
  }
}`

Can I use facts with subfucts in the plugin?

**Comment by ekohl** [comment] 2022-02-22 16:57
While I don't know the answer, I think this is a duplicate of https://github.com/theforeman/foreman_default_hostgroup/issues/45.

**Closed as completed by ekohl** 2022-02-22 16:57 UTC
